swagger: '2.0'
info:
  title: Data Inventory API
  description: API used to keep track of data being given to other departments via ETL jobs or APIs.
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/data-inventory-api
schemes:
  - https
basePath: /v1/
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/ResultObject'

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObject:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
  Attributes:
    properties:
      name:
        type: string
        description: Name of API or Talend job
      description:
        type: string
        description: >
          Short description of API or Talend job. This shouldn't include anything that could be 
          populated by other fields in the attributes object.
      mou:
        type: string
        format: url
        description: Link to memorandum of understanding document
      consumingEntities:
        type: array
        description: What entities are consuming and have access to this data?
        items:
          properties:
            entityID:
              type: string
              description: Able to be generated by the client.
            entityName:
              type: string
            entityContactName:
              type: string
            entityEmail:
              type: string
            entityPhone:
              type: string
            entityUrl:
              type: string
              format: url
              description: Website for entity
            internal:
              type: boolean
              description: >
                If false, the entity is a third-party vendor goverened outside the scope of the university.
      providedData:
        type: array
        description: What data is being exposed or transferred?
        items:
          $ref: "#/definitions/DataSource"

  DataSource:
    properties:
      sourceID:
        type: string
        description: Able to be generated by the client.
      sourceDescription:
        type: string
      sourceType:
        type: string
        description: > 
          Type of data source being accessed directly. Possible values are "api", "database", or "other".
      otherSourceType:
        type: string
        description: "Explanation if sourceType is 'other'"
      database:
        type: string
        description: Name of database being accessed, if applicable.
      databaseSchema:
        type: string
        description: Name of database schema being used, if applicable.
      querySQL:
        type: string
        description: SQL query being used to get fields, if applicable.
      apiUrl:
        type: string
        format: url
        description: Url of API being called, if applicable.
      internal:
        type: boolean
        description: >
          If false, the data source is hosted and maintained outside of the university.
      fields:
        type: array
        items:
          type: string
          description: Plain english name of field being provided
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
