swagger: '2.0'
info:
  title: Data Inventory API
  description: API used to keep track of data being given to other departments via ETL jobs or APIs.
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/data-inventory-api
schemes:
  - https
basePath: /v1/
consumes:
  - application/json
produces:
  - application/json
paths:
  /datainventory:
    get:
      description: "Get all dataInventory objects. Can be filtered by query parameters."
      parameters:
        - name: type
          in: query
          description: >
            Filter by dataInventory object type. Valid types are "API", "Talend", or "Other".
          collectionFormat: multi
          required: false
          type: string
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ResultObject'
        400:
          description: Bad request. Invalid type parameter.
          schema:
            $ref: '#/definitions/Error'
    
    post:
      description: Add a new dataInventory object.
      parameters:
        - name: dataInventory object
          in: body
          description: JSON representation of dataInventory object
          required: true
          schema:
            $ref: '#/definitions/ResultObject'
        - $ref: '#/parameters/pretty'
      responses:
        201:
          description: dataInventory object successfully created.
          schema:
            $ref: '#/definitions/ResultObject'
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Error'
        409:
          description: "Conflict: Client generated ID already exists or type is invalid."
          schema:
            $ref: '#/definitions/Error'
            
  /datainventory/{id}:
    get:
      description: Get a single dataInventory object by ID.
      parameters:
        - name: id
          in: path
          description: ID of dataInventory object
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/ResultObject'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ResultObject'
    
    patch:
      description: Update an existing dataInventory object
      parameters:
        - name: id
          in: path
          description: ID of dataInventory object
          required: true
          type: string
        - name: dataInventory object
          in: body
          description: JSON representation of dataInventory object
          required: true
          schema:
            $ref: '#/definitions/ResultObject'
      responses:
        200:
          description: dataInventory object successfully updated.
          schema:
            $ref: '#/definitions/ResultObject'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        409:
          description: "Conflict: Type and/or id do not match server's endpoint"
          schema:
            $ref: '#/definitions/Error'
    
    delete:
      description: Delete an existing dataInventory object
      parameters:
        - name: id
          in: path
          description: ID of dataInventory object
          required: true
          type: string
      responses:
        204:
          description: dataInventory object successfully deleted
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObject:
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
  ResourceObject:
    properties:
      id:
        type: string
        description: "UUID as specified here: https://tools.ietf.org/html/rfc4122.html"
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
  Attributes:
    properties:
      name:
        type: string
        description: Name of API or Talend job
      description:
        type: string
        description: >
          Short description of API or Talend job. This shouldn't include anything that could be 
          populated by other fields in the attributes object.
      type:
        type: string
        description: >
          Type of mechanism being used to deliver the data. Possible values are "API", "Talend", or "Other".
      otherType:
        type: string
        description: 'Explanation if type is "Other".'
      mou:
        type: string
        format: url
        description: Link to memorandum of understanding document
      consumingEntities:
        type: array
        description: What entities are consuming and have access to this data?
        items:
          properties:
            entityID:
              type: string
              description: Able to be generated by the client.
            entityName:
              type: string
              description: Department or vendor name
            entityContactName:
              type: string
            entityEmail:
              type: string
            entityPhone:
              type: string
            entityUrl:
              type: string
              format: url
              description: Website for entity
            internal:
              type: boolean
              description: >
                If false, the entity is a third-party vendor goverened outside the scope of the university.
      providedData:
        type: array
        description: What data is being exposed or transferred?
        items:
          $ref: "#/definitions/DataSource"
  DataSource:
    properties:
      sourceID:
        type: string
        description: Able to be generated by the client.
      sourceDescription:
        type: string
      sourceType:
        type: string
        description: > 
          Type of data source being accessed directly. Possible values are "api", "database", or "other".
      otherSourceType:
        type: string
        description: "Explanation if sourceType is 'other'"
      database:
        type: string
        description: Name of database being accessed, if applicable.
      databaseSchema:
        type: string
        description: Name of database schema being used, if applicable.
      querySQL:
        type: string
        description: SQL query being used to get fields, if applicable.
      apiUrl:
        type: string
        format: url
        description: Url of API being called, if applicable.
      internal:
        type: boolean
        description: >
          If false, the data source is hosted and maintained outside of the university.
      fields:
        type: array
        items:
          type: string
          description: Plain english name of field being provided
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
